---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-ip-hmrc
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-ip-hmrc
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-ip-hmrc
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: vault-sidekick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
        imagePullPolicy: Always
        securityContext:
           capabilities:
             drop:
               - SETUID
               - SETGID
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - -output=/etc/nginx/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=pttg-ip-hmrc.${NAMESPACE}.svc.cluster.local,file=/etc/nginx/secrets/pttg-ip-hmrc,fmt=bundle
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
        volumeMounts:
          - mountPath: /etc/nginx/secrets
            name: secrets
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
      - name: javapki
        emptyDir:
          medium: "Memory"
